stages:
  - build
  - deploy

.build: &build
  stage: build
  image: docker:latest
  services:
    - docker:18.09.7-dind
  script:
    - echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
    - docker build . -t $DOCKER_USERNAME/alehub_api:$TAG
    - docker push $DOCKER_USERNAME/alehub_api:$TAG

.deploy: &deploy
  stage: deploy
  image: linuxserver/openssh-server:amd64-latest
  before_script:
    - eval "$(ssh-agent)"
    - ssh-add <(echo "$PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "$SSH_CONFIG" > ~/.ssh/config

# DEVELOP ENVIRONMENT
develop-build:
  <<: *build
  variables:
    TAG: dev
  before_script:
    - echo -e "$NODE_ENV" > .env
    - cp .env.dev .env
  only:
    - develop

develop-deploy:
  <<: *deploy
  script:
    - ssh develop "cd ~/app/ezsale/ezsale-alehub && ./deploy.sh api && exit"
  only:
    - develop


# STAGE ENVIRONMENT
staging-build:
  <<: *build
  variables:
    TAG: staging  
  only:
    - staging

staging-deploy:
  <<: *deploy
  script:
    - ssh develop "cd ~/app/alehub-staging && ./deploy.sh api && exit"
  only:
    - staging

# PRODUCTION ENVIRONMENT
prod-build:
  <<: *build
  variables:
    TAG: latest
  only:
    - master

prod-deploy:
  <<: *deploy
  when: manual
  script:
    - ssh production "cd /root/app/alehub && ./deploy.sh api && exit"
  only:
    - master
