export const GROUP_CAREERS = [
  {
    name: 'Kinh doanh/Bán hàng',
    careers: [
      'Tư Vấn Bán Hàng',
      'Telesale',
      'Giám Sát Bán Hàng',
      'Sale thị trường',
      'Chăm sóc khách hàng',
    ],
  },
  {
    name: 'Ngân hàng/Tài chính',
    careers: [
      'Giao dịch viên',
      'Môi giới chứng khoán',
      'Phân tích tài chính',
      'Xử lý nợ',
      'Quản trị rủi ro',
      'Quản lý tín dụng',
      'Thẩm định tín dụng',
      'Đầu tư dự án',
      'Quan hệ khách hàng',
    ],
  },
  {
    name: 'Kế toán/Kiểm toán',
    careers: [
      'Kế Toán Thuế',
      'Kế Toán Kho',
      'Kế Toán Tổng Hợp',
      'Kế Toán Công Nợ',
      'Kế Toán Sản Xuất',
      'Kế Toán Bán Hàng',
      'Kế Toán Quản Trị',
      'Kiểm Toán',
      'Kiểm Soát Nội Bộ',
      'Thủ Quỹ',
      'Kế Toán Xây Dựng',
      'Kế toán thanh toán',
    ],
  },
  {
    name: 'Giáo dục đào tạo',
    careers: [
      'Tâm lý học',
      'Quản lý giáo dục',
      'Đào tạo',
      'Giáo dục mầm non',
      'Giáo dục phổ thông',
      'Ngoại ngữ',
      'Trợ giảng',
      'Giảng viên',
      'Tuyển sinh',
      'Giáo dục đặc biệt',
      'Thể chất',
    ],
  },
  {
    name: 'Công nghệ thông tin',
    careers: ['CNTT - Phần cứng / Mạng', 'CNTT - Phần mềm'],
  },
  {
    name: 'Sản xuất',
    careers: [
      'Dệt may / Da giày',
      'Xây dựng',
      'Sản xuất',
      'Bảo trì / Sửa chữa',
      'An toàn lao động',
    ],
  },
  {
    name: 'Quảng cáo/Marketing',
    careers: [
      'Nội Dung',
      'Seeding (Forum/Facebook)',
      'SEO',
      'Facebook Ads',
      'Google Ads(AdWords)',
      'Offline Marketing (Báo/Đài/Truyền Hình)',
      'Social Marketing',
      'Digital Marketing',
      'Planner',
    ],
  },
  {
    name: 'Hành Chính/Văn Phòng',
    careers: [
      'Hành chính / Văn phòng',
      'Nhân sự/Tuyển Dụng',
      'Hoạch định / Dự án',
      'Quản lý điều hành',
      'Thư ký / Trợ lý/Lễ Tân',
    ],
  },
  {
    name: 'Lao động phổ thông',
    careers: ['Bảo Vệ', 'Lao Công/Tạp Vụ', 'Giúp Việc', 'Công nhân'],
  },
  {
    name: 'Luật/Pháp chế',
    careers: ['Luật', 'Pháp chế', 'Luật hành chính'],
  },
  {
    name: 'Biên dịch viên',
    careers: ['Biên phiên dịch'],
  },
  {
    name: 'Thiết kế',
    careers: [
      'UI/UX',
      'Thiết Kế 3D',
      'Thiết Kế 2D',
      'Thiết Kế Sản Phẩm',
      'Thiết Kế Game',
      'Thiết Kế Thời Trang',
    ],
  },
];

// 'Kế toán',
// 'Hành chính - Văn phòng',
// 'Nhân viên kinh doanh',
// 'Chăm sóc viên',
// 'Telesales',
// 'Nhân viên chăm sóc khách hàng',
// 'Hành chính - Nhân sự',
// 'Ngân hàng',
